# Generated by Django 3.1.1 on 2020-10-20 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predBreed', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('body', models.TextField()),
                ('day', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='adoptPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breedName', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('health', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('ageYears', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('addr', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('upForAdoption', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=6)),
                ('details', models.TextField()),
                ('day', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
