# Generated by Django 3.1.1 on 2020-09-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggoWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
