# Generated by Django 3.1.1 on 2020-10-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggoWebsite', '0003_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='adoptPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breedName', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('health', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('ageYears', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('addr', models.TextField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('upForAdoption', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=6)),
                ('details', models.TextField()),
            ],
        ),
    ]
