# Generated by Django 3.1.1 on 2020-10-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggoWebsite', '0005_auto_20201016_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptpost',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
